apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-service
  name: mongodb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-service
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-service
  labels:
    app: mongodb-service
spec:
  selector:
    matchLabels:
      app: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-service
      name: mongodb-service


    spec:
      containers:
        - image: mongo:latest
          name: mongodb-service

          ports:
            - containerPort: 27017
              name: mongodb-service